name: API CI
on: [push]
jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -m venv .venv && source .venv/bin/activate && pip install -e .
      - run: python -c "import fastapi, httpx; print('ok')"